<!DOCTYPE HTML>
<html lang="ja">
<head>
    <meta http-equiv="Content-Type" content="width=device-width, initial-scale=1.0" >
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="X-UA-Compatible" >
    <title>Login</title>
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="<?php echo TEMPLATE_URL?>/bootstrap3/js/bootstrap.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_URL?>/bootstrap3/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_URL?>/bootstrap3/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_URL?>/css/stylesheet.css">
</head>
<body>
<?php echo $this->layout()->content?>
</body>
</html>

