<!DOCTYPE html>
<html>
<head>
		<meta http-equiv="Content-Type" content="width=device-width, initial-scale=1.0" charset="UTF-8">
        
		<title><?php echo $this->title; ?></title>
        <!--
		<link rel="stylesheet" type="text/css" href="<?php //echo TEMPLATE_URL?>/css/jqueryui.smoothness/jquery-ui-1.8.21.custom.css">
		<link rel="stylesheet" type="text/css" href="<?php //echo TEMPLATE_URL?>/css/stylesheet.css">

		<script src="<?php //echo TEMPLATE_URL?>/js/jquery-ui-1.8.21.custom.min.js" type="text/javascript"></script>
		<script src="<?php //echo TEMPLATE_URL?>/js/const.js" type="text/javascript"></script>
		<script src="<?php //echo TEMPLATE_URL?>/js/jquery.utility.js" type="text/javascript"></script>
		<script src="<?php //echo TEMPLATE_URL?>/js/jquery.fixedtable.js" type="text/javascript"></script>
		<script src="<?php //echo TEMPLATE_URL?>/js/tooltip.js?<?php //echo time();?>" type="text/javascript"></script>
        -->
        <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
      
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#las-bar1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="las-bar1">
          <ul class="nav navbar-nav">
                <li  class="<?php echo $this->index_act; ?>"><a href="index">Dashboard</a></li>
                <li class="<?php echo $this->customer_act; ?>"><a href="customer">Customer</a></li>
            <li class="<?php echo $this->user_act; ?>"><a href="user">User</a></li >
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
                <?php if($this->user['Permission'] >= 90){?>
    				<li>
    					<a href="/user">Manage User</a>
    				</li>
				<?php }?>
				<li><a href="/customer">Manage Customer</a></li>
    				
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-cog" ></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li class="divider"></li>
                   	<li><a href="/index/login">Log Out</a>	</li>
                  </ul>
                </li>
          </ul>

          
        </div><!-- /.navbar-collapse -->
        
      </div><!-- /.container-fluid -->
    </nav>
    
    <div class="container-fluid" style="margin: 0px 50px 0 50px;">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xm-12">
            <!--
                 <img src="<?php echo TEMPLATE_URL?>/images/logo.png" class="logo"> 
               	<h1 class="visible-lg visible-md"> <span class="glyphicon glyphicon-user" ></span>CUSTOMER MANAGEMENT</h1>
               	<h3 class="visible-sm"> <span class="glyphicon glyphicon-user" ></span>CUSTOMER MANAGEMENT</h3>
                -->
            </div>
        </div>
        <?php echo $this->layout()->content?>

    </div>
</body>
</html>

<script src="<?php echo TEMPLATE_URL?>/bootstrap3/js/bootstrap.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_URL?>/bootstrap3/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_URL?>/bootstrap3/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_URL?>/css/stylesheet.css">