<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="pull-left">
            <h4>List customer</h4>
        </div>
        <div class="col-lg-1 c"></div>
        <div class="pull-left">
            <div class="input-group">
              <input type="text" class="form-control">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="table-responsive">
            <table class="table table-bordered" style="margin-bottom: 0px;">
           	    <thead>
            		<tr>
            			<th width="50px" style="text-align: center;">#</th>
            			<th width="80px">ID</th>
            			<th width="200px">Name</th>
            			<th width="200px">Kana Name</th>
            			<th width="200px">Short Name</th>
            			<th >Tel</th>
            		</tr>
            	</thead>
            </table>
            <table class="table table-bordered table-hover">
                <tbody>
                    <?php foreach ($this->data as $row) : ?>
        			<tr onmouseout="hidetip()"
        				onmouseover="showtip('<?php
        					echo 'Created by '. $row["CreatedUserId"]. ' on '.date_format(date_create($row["CreatedDate"]), 'Y-m-d');
        					if($row["UpdatedDate"] != ''){
        						echo '<br/>'.'Updated by '. $row["UpdatedUserId"]. ' on '.date_format(date_create($row["UpdatedDate"]), 'Y-m-d');
        					}
        					?>')">
        				<td width="50px" style="text-align: center;"><input type="checkbox" name="checkbox"></td>
        			
        				<td width="80px" style="text-align: right;"><a
        					href="/customer/edit/id/<?php echo $row['CustomerId']; if(isset($this->keyword)) echo '/keyword/'.$this->keyword?>"><?php echo sprintf("%04d", $row['CustomerId']); ?>
        				</a>
        				</td>
        				<td width="200px"><a
        					href="/customer/edit/id/<?php echo $row['CustomerId']; if(isset($this->keyword)) echo '/keyword/'.$this->keyword?>"><?php echo html_entity_decode($row['CustomerName']); ?>
        				</a>
        				</td>
        				<td width="200px"><?php echo html_entity_decode($row['CustomerNameKana']); ?>
        				</td>
        				<td width="200px"><?php echo html_entity_decode($row['CustomerShortName']); ?>
        				</td>
        				<td ><?php echo $row['Tel']; ?></td>
        				
        			</tr>
        			<?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>


<div style="height: 32px">
	<h2 style="margin-bottom: 10px; float: left !important">Customer List</h2>
	<button id="search" class="search-button" type="button"></button>
	<input type="text" id="search-input" class="search-box" maxlength="30"
		placeholder="Search" onkeypress="keyDown(event)"
		value="<?php echo $this->keyword;?>">
</div>
<div class="list-button">
	<button id="add-row" class="button add" type="button"
		onclick="location.href='/customer/edit/<?php if(isset($this->keyword)) echo 'keyword/'.$this->keyword?>'">Add</button>
	<button id="delete" class="button delete" type="button">Delete</button>
</div>

<script src="/public/js/m0020.js?<?php echo time();?>" type="text/javascript"></script>